### ISSUE TITLE
Lastest test contens missing the last frame

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/Test-Content#12] opened 2021-05-13 12:51 UTC
I didn't check all but noticed some of the contents missing the last frame.
For example:
https://dash.akamaized.net/WAVE/vectors/avc_sets/15_30_60/t20/
This plays to frame number 3599. I think the last frame should be 3600 for 60fps contents.

**Comment by rbouqueau** [comment] 2021-05-25 12:45
Frame 0 goes from time 0 to time 1/60. 60s is 3600/60 which means that frame 3600 starts at 60s. So the last frame is 3599. Am I missing something?

**Comment by jpiesing** [comment] 2021-05-25 12:50
The mezzanine content includes an extra coloured frame at the start and end so if you encode exactly frames 0 to 3599 inclusive, you will get the coloured frame at the start and miss the last frame of video and the coloured frame at the end.

**Comment by nicholas-fr** [comment] 2021-05-25 12:54
Indeed, the mezzanine content contains 60 seconds of content + 2 additional frames indicating the start and end.
So in total the length is slightly longer than 60 seconds.

**Comment by rbouqueau** [comment] 2021-05-25 13:40
> I think the numbered mezzanine goes from frame 1

Yes but there is a green frame as frame 0.

> Indeed, the mezzanine content contains 60 seconds of content + 2 additional frames indicating the start and end.

For everyone's information the script I wrote explicitly stops at 60s. Shoud it behave otherwise?

**Comment by jpiesing** [comment] 2021-05-25 13:42
> For everyone's information the script I wrote explicitly stops at 60s. Shoud it behave otherwise?

Yes. See @nicholas-fr 's explanation. The duration of the content is 60s + 2 frames.

**Comment by yanj-github** [comment] 2021-05-25 13:47
It is fine for us to make a change and check last frame is 3599 instead of 3600 if the contents supposed to be end at 3599. 
However, I think OF wont be able to observe frame 0 as it has no QR code.

**Comment by rbouqueau** [comment] 2021-05-25 14:12
The generation script could also ignore the first and last frames.

**Comment by jpiesing** [comment] 2021-05-25 14:23
> The generation script could also ignore the first and last frames.

The first and last frames were put there for a reason - to make it easy for people to trivially detect whether all frames are output.

**Comment by andyburras** [comment] 2021-05-25 14:32
I think the issue is arising from that they don't have QR codes, so they are not part of the test. If for e.g. the test configuration passes to the O.F. an expected duration of 60 seconds, then that needs to be 60 seconds of video *with* QR codes

**Comment by jpiesing** [comment] 2021-05-25 14:33
> I think the issue is arising from that they don't have QR codes, so they are not part of the test. If for e.g. the test configuration passes to the O.F. an expected duration of 60 seconds, then that needs to be 60 seconds of video _with_ QR codes

@nicholas-fr ?

**Comment by rbouqueau** [comment] 2021-05-25 14:34
> The first and last frames were put there for a reason - to make it easy for people to trivially detect whether all frames are output.

Why don't we make them part of the 60s then? Otherwise we'll emit a finale segment with 2 frames (that's ok but is it what we mean?).

**Comment by andyburras** [comment] 2021-05-25 15:36
Adding the QR codes would definitely benefit the accuracy of the observations

**Comment by jpiesing** [comment] 2021-06-25 18:52
@andyburras @yanj-github I believe this is now addressed - at least it is in the C0028 test run I shared with Yan a few days ago. If you agree, please close this issue.

**Closed** 2021-06-25 19:36 UTC
